[general]
id = "cs1-ff00_0_110-1"
config_dir = "gen/ASff00_0_110"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_110-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.12:30452"

[api]
addr = "127.0.0.12:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"

[drkey.lvl1_db]
connection = "gen-cache/cs1-ff00_0_110-1.lvl1.db"

[drkey.sv_db]
connection = "gen-cache/cs1-ff00_0_110-1.sv.db"

[drkey.delegation]
colibri = [ "127.0.0.11",]
